apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    labels:
        app: api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            hostNetwork: true
            containers:
                - name: api-container
                  image: gabrielvrfreire/nodejs-nest-api:latest
                  ports:
                      - containerPort: 3000
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
            volumes:
                - name: node-modules-volume
                  emptyDir: {}
